name = "bessie-dev"
main = "worker.js"
compatibility_date = "2026-08-04"
workers_dev = true
preview_urls = true
routes = [
  { pattern = "bessie.dev", custom_domain = true, zone_name = "bessie.dev" },
  { pattern = "www.bessie.dev", custom_domain = true, zone_name = "bessie.dev" },
]
[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/appcast.xml", "/install"]
